name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

  checks:
      runs-on: ubuntu-latest
      continue-on-error: true
      needs: build
      steps:
      - uses: actions/checkout@v4
      - name: Checks
        run: RUSTFLAGS="-Dwarnings" cargo check --all --all-targets
      - name: Clyppy
        run: RUSTFLAGS="-Dwarnings" cargo clippy --all --all-targets
        
  tests:
      runs-on: ubuntu-latest
      continue-on-error: true
      needs: build
      steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
        

    
