name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Checks
      run: cargo check --all --all-targets
    - name: Clyppy
      run: cargo clippy --all --all-targets
    - name: Run tests
      run: cargo test --verbose
